### PR TITLE
update TileDB-VCF to 0.29.0

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
Need to fix the sha256:

```
RuntimeError: SHA256 mismatch: '9c160f2435bff60ff53401fbb72cd9d061a8af073ab37c0e544bcf2084cfcbe7' != '25c1f2c5c8e3846ebc3de0ce7069b365dc22ffadede9036d8338a072eabc9137'
```

**Comment by jdblischak** [comment]
The linux-64 job is [failing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38035&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=19870002-9ea0-5c64-a2c3-e2872fb3f101) with the same Python 3.7 error we saw last week in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/83

```
include/python3.7m/Python.h:44:10: fatal error: crypt.h: No such file or directory
```

I think it's time to drop the Python 3.7 build just like we did for tiledbsoma-feedstock. cc @ihnorton @Shelnutt2

**Comment by Shelnutt2** [comment]
> The linux-64 job is [failing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38035&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=19870002-9ea0-5c64-a2c3-e2872fb3f101) with the same Python 3.7 error we saw last week in [TileDB-Inc/tiledbsoma-feedstock#83](https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/83)
> 
> ```
> include/python3.7m/Python.h:44:10: fatal error: crypt.h: No such file or directory
> ```
> 
> I think it's time to drop the Python 3.7 build just like we did for tiledbsoma-feedstock. cc @ihnorton @Shelnutt2

Lets drop it!

**Comment by ihnorton** [comment]
Re-running CI to check sc-38823

**Comment by jdblischak** [comment]
@awenocur you can drop the py37 build by deleting the following from `conda_build_config.yaml` and then rerendering (note that this will also add a py311 build, which should be fine)

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/6eef8ee5b8fef52e25f7f5455080bf454ee638a2/recipe/conda_build_config.yaml#L9-L23

**Comment by ihnorton** [comment]
@awenocur please also re-render. [this run](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38070&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b) failed with sc-38823, but it picked up the old build not the new one with the updated SDK dependencies.

**Comment by jdblischak** [comment]
Please rebase onto master to include https://github.com/TileDB-Inc/tiledb-vcf-feedstock/commit/9ba78d502af15702667257790e97d07c6c7875d5 from #112, which dropped the linux-64 py37 build

**Comment by jdblischak** [comment]
More [conda solver errors](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38265&view=results) when trying to build the Python client:

* linux-64: related to libgoogle-cloud, similar to what we are observing in tiledbsoma-feedstock (eg https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/92)
* win-64, osx-64, osx-arm64: related to aws-sdk-cpp, presumably because tiledb 2.20 now depends on the aws packages from conda-forge (https://github.com/conda-forge/tiledb-feedstock/pull/241)

Until we move away from pyarrow 11, I suspect the conda solver errors will continue to be problematic:

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/9ba78d502af15702667257790e97d07c6c7875d5/recipe/conda_build_config.yaml#L9-L14

arrow 11 is no longer receiving the conda-forge migrator updates, so it isn't built against the latest aws-sdk-cpp versions, and thus is unable to be installed in the same environment as tiledb 2.20

https://github.com/conda-forge/arrow-cpp-feedstock/blob/161d0c0ef5259f93699c4c9d0b63816a872c6d1f/conda-forge.yml#L4-L9

**Comment by ihnorton** [comment]
I believe we can fix the osx-arm64 conflict in a build-bump by making the pyarrow `>=` condition depend on python version.

**Comment by jdblischak** [comment]
> I believe we can fix the osx-arm64 conflict in a build-bump by making the pyarrow `>=` condition depend on python version.

The [error](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38345&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba) is:

```python
ImportError: cannot import name 'set_timezone_db_path' from 'pyarrow.lib' (/Users/runner/miniforge3/conda-bld/tiledb-vcf_1709872988870/_build_env/venv/lib/python3.9/site-packages/pyarrow/lib.cpython-39-darwin.so)
```

It's unclear to me why only osx-arm64 would need a different pyarrow version for different python versions. My initial guess would be a cross-compilation problem, since osx-arm64 is the only cross-compiled job in this feedstock.

**Comment by jdblischak** [comment]
>It's unclear to me why only osx-arm64 would need a different pyarrow version for different python versions.

The osx-arm64 build was fixed in in #114 

In the [failing build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38345&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba) in this PR, pyarrow 11 was installed in the build env and pyarrow 15 in the host env.

In the [passing build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38366&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba) from #114, pyarrow 15 was installed in both the build and host envs.

Honestly unclear why pyarrow 11 was installed in the build env in this PR. It didn't have any minimum or maximum contraints in the `build` requirements, the same as in #114

**Pull request merged**
