### PR TITLE
Loosen pyarrow pin

### PR DESCRIPTION
**Pull request by jdblischak**
Background:

* Currently getting aws-sdk-solver errors in https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/111, likely due to pyarrow 11 no longer being built against the latest conda-forge pins
* TileDB-VCF was migrated to use the arrow C data interface in https://github.com/TileDB-Inc/TileDB-VCF/pull/653
* tiledb-feedstock now installs aws-sdk-cpp from conda-forge (https://github.com/conda-forge/tiledb-feedstock/pull/241)
* We recently dropped the py37 builds in https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/112

### CODE REVIEW

**Review by awenocur — APPROVED** [review]

**Comment by jdblischak** [comment]
At least we're making progress. No more aws-sdk-cpp solver errors, Now they're all failing with the libgoogle-cloud solver errors!

**Comment by jdblischak** [comment]
I'm working on fixing the solver errors upstream in tiledb-feedstock, eg https://github.com/conda-forge/tiledb-feedstock/pull/246

**Comment by jdblischak** [comment]
I just merged https://github.com/conda-forge/tiledb-feedstock/pull/246. It builds tiledb 2.19 against google-cloud-cpp 2.21. Once the binaries are uploaded, I'll restart the CI here to see if that helps the solver

**Review by Shelnutt2 — APPROVED** [review]

**Comment by jdblischak** [comment]
So I built libtiledb 2.19 against libgoogle-cloud 2.21, but the conda solver is still [failing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38342&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) because it still hasn't been built against the latest abseil:

```
    Could not solve for environment specs
    The following packages are incompatible
    ├─ libabseil ==20240116.1 cxx17_h59595ed_2 is requested and can be installed;
    ├─ libcurl ==8.5.0 hca28451_0 is requested and can be installed;
    ├─ libgoogle-cloud ==2.21.0 h72bcb37_2 is requested and can be installed;
    ├─ libtiledbvcf 0.28.1**  is installable with the potential options
    │  ├─ libtiledbvcf 0.28.1 would require
    │  │  └─ tiledb 2.19.*  with the potential options
    │  │     ├─ tiledb [2.19.0|2.19.1] would require
    │  │     │  └─ libcurl >=7.88.1,<8.0a0 , which conflicts with any installable versions previously reported;
    │  │     ├─ tiledb [2.19.0|2.19.1] would require
    │  │     │  └─ openssl >=1.1.1w,<1.1.2a , which can be installed;
    │  │     ├─ tiledb [2.19.0|2.19.1] would require
    │  │     │  └─ libgoogle-cloud >=2.12.0,<2.13.0a0 , which conflicts with any installable versions previously reported;
    │  │     └─ tiledb 2.19.1 would require
    │  │        └─ libabseil >=20230802.1,<20230803.0a0 , which conflicts with any installable versions previously reported;
    │  └─ libtiledbvcf 0.28.1 conflicts with any installable versions previously reported;
    └─ openssl ==3.2.1 hd590300_0 is not installable because it conflicts with any installable versions previously reported.
```

I'm hoping a bot will auto-open the libabseil migration PR (just like the one it sent to update 2.20 in main, https://github.com/conda-forge/tiledb-feedstock/pull/245). But if that doesn't happen soon, I'll try to manually perform the migration.

**Comment by ihnorton** [comment]
Migration here: https://github.com/conda-forge/tiledb-feedstock/pull/250

**Comment by jdblischak** [comment]
Superseded by https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/111/commits/7aede11743f5a57f9dbbfa05aea806a1af9808b8 in #111, merged as https://github.com/TileDB-Inc/tiledb-vcf-feedstock/commit/5f11910511df9268ff0a37eaa7fa8630603fff29

**Pull request closed without merging**
