### PR TITLE
update TileDB-VCF to 0.25.0

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Comment by awenocur** [comment]
[sc-31619]

**Review by ihnorton — CHANGES_REQUESTED** [review]
We need to bump the pin to `2.16.*`: https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/a2f0688bcf277e52d531b4793689cc94344f00ed/recipe/meta.yaml#L32

**Review by ihnorton — APPROVED** [review]
LGTM after CI

**Comment by ihnorton** [comment]
Close/open to kick-off again to pull in https://github.com/conda-forge/tiledb-feedstock/pull/200

**Pull request merged**
