### PR TITLE
update TileDB-VCF to 0.28.1

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]
Does 0.28.1 require libtiledb >=2.19.1? If yes the pin should be updated. It's currently set to `2.19.*`

**Comment by awenocur** [comment]
> Does 0.28.1 require libtiledb >=2.19.1?

It does not rely on anything introduced in 2.19.1.

**Comment by jdblischak** [comment]
The [AWS error on osx](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37848&view=logs&j=5919e0e2-8634-58c1-7e2d-cc5398f52f3f&t=f395cd69-c266-53d9-bd41-0b417b09501f) is a known issue:

```
+ python test-api.py
Fatal error condition occurred in /Users/runner/miniforge3/conda-bld/aws-c-common_1703906860368/work/source/allocator.c:172: allocator != ((void*)0)
Exiting Application
```

It's still the same error that was first identified in https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/105#issuecomment-1856187919

**Comment by jdblischak** [comment]
@awenocur The linux-64 job of the merge commit 250b8d9 [failed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38090&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) because of the Python 3.7 error identified in https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/111#issuecomment-1964593566. If you want linux-64 binaries for 0.28.1, you'll need to submit a follow-up PR to drop Python 3.7, and merge it prior to merging #111

**Comment by jdblischak** [comment]
0.28.1 now available for linux-64, uploaded from https://github.com/TileDB-Inc/tiledb-vcf-feedstock/commit/9ba78d502af15702667257790e97d07c6c7875d5

https://anaconda.org/tiledb/libtiledbvcf/files?version=0.28.1

**Pull request merged**
