### PR TITLE
Update TileDB-VCF to 0.33.0 

### PR DESCRIPTION
**Pull request by awenocur**

### CODE REVIEW

**Comment by jdblischak** [comment]
TileDB 2.24.0 hasn't been released yet, so there is no conda binary. The latest is [2.24.0-rc0](https://github.com/TileDB-Inc/TileDB/releases/tag/2.24.0-rc0)

**Comment by jdblischak** [comment]
It's failing with a conda solver error:

```sh
Encountered problems while solving:
  - package tiledb-2.24.0-hcda1485_0 requires libcurl >=8.8.0,<9.0a0, but none of the providers can be installed
```

I am able to reproduce this locally:


```sh
mamba create --dry-run -n test \
  -c conda-forge -c tiledb --override-channels \
  "htslib>=1.15" tiledb=2.24
## The following packages are incompatible
## ├─ htslib >=1.15  is installable with the potential options
## │  ├─ htslib [1.16|1.19] would require
## │  │  └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed;
## │  ├─ htslib [1.16|1.19] would require
## │  │  └─ libcurl >=7.88.1,<8.0a0 , which can be installed;
## │  └─ htslib [1.16|1.19] would require
## │     └─ libcurl >=7.87.0,<8.0a0 , which can be installed;
## └─ tiledb 2.24**  is not installable because it requires
##    ├─ libcurl >=8.8.0,<9.0a0 , which conflicts with any installable versions previously reported;
##    └─ libzlib >=1.3.1,<2.0a0 , which conflicts with any installable versions previously reported.
```

I am going to rerender our [htslib-feedstock](https://github.com/TileDB-Inc/htslib-feedstock) to see if that fixes it.

**Comment by jdblischak** [comment]
I rerendered htslib-feedstock in https://github.com/TileDB-Inc/htslib-feedstock/pull/17, and the binaries have already been [uploaded](https://anaconda.org/tiledb/htslib/files)

It could take an hour or so for all the CDN mirrors to sync, but I am already to solve it locally using the new binary (build number 1)

```sh
mamba create --dry-run -n test \
  -c conda-forge -c tiledb --override-channels \
  "htslib>=1.15" tiledb=2.24
##   + tiledb                          2.24.0  h8ea5c1f_0        conda-forge        4MB
##   + htslib                            1.19  h18cb6ac_1        tiledb             1MB
```

**Comment by jdblischak** [comment]
The current failures are during the test section of Python 3.12. It requires numpy 1.26 to be installed, but we have it pinned at runtime to a max of `1.24`

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/512f6a9207eb4e758f4be00f031d49d1012b98f3/recipe/meta.yaml#L84

The easiest solution would be to bump the maximum numpy at runtime. If that's not possible, we could 1) drop the python 3.12 build by specifying the python variants explicitly in `conda_build_config.yaml`, or 2) define numpy restraints based on the python version using the jinja2 preprocessing selectors `[py < 312]` and `[py >= 312]`

**Comment by jdblischak** [comment]
Shoot. Now there is a brand new conda solver error related to libgoogle-cloud-storage, which I assume is caused by the migration to libgoogle-cloud 2.25, which was started 10 hours by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6029

```
Packaging tiledbvcf-py
Reloading output folder (local): ...working... done
Solving environment (_h_env): ...working... failed
WARNING: failed to get package records, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("libtiledbvcf==0.33.0=h653c503_0"), MatchSpec("tiledb[version='>=2.24.0,<2.25.0a0']")}
Encountered problems while solving:
  - package libtiledbvcf-0.33.0-h653c503_0 requires tiledb >=2.24.0,<2.25.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ libgoogle-cloud-storage 2.25.0.* h3d9a0c8_0 is requested and can be installed;
└─ libtiledbvcf 0.33.0.*  is not installable because it requires
   └─ tiledb >=2.24.0,<2.25.0a0 , which requires
      └─ libgoogle-cloud-storage >=2.24.0,<2.25.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by johnkerl** [comment]
I just re-launched CI

**Comment by jdblischak** [comment]
Ugh. `upper_bound` is `<`, not `<=`. Fixing now

```
  - nothing provides requested numpy >=1.16,<1.26,>=1.26.4,<2.0a0
```

**Comment by jdblischak** [comment]
This one is ready to go. CI is green except win-64, which is know to have been failing for months.

@awenocur please remove the draft status

**Review by johnkerl — APPROVED** [review]

**Pull request merged**
