### PR TITLE
Update TileDB-VCF to 0.36.0

### PR DESCRIPTION
**Pull request by dudoslav**
Support for numpy 2.

Re-render/

### CODE REVIEW

**Review by jdblischak — CHANGES_REQUESTED** [review]
Since this feedstock isn't part of conda-forge, we'll need to manually migrate to numpy2.

Please copy the numpy2 migration file `.ci_support/migrations/numpy2.yaml` from tiledb-py-feedstock and then rerender to bump the numpy pins

https://github.com/conda-forge/tiledb-py-feedstock/blob/e618f17eabcbeaae2644ed1a480a010f4073e072/.ci_support/migrations/numpy2.yaml

**Comment by dudoslav** [comment]
Thanks @jdblischak , copied and re-rendered

**Comment by jdblischak** [comment]
Failing win-64 build is a known problem that we can ignore.

The osx-64 and osx-arm64 compilation errors are new and are presumably due to the upgrade from clang 16 to 18. Any ideas how we can work around this? Worse case we can try pinning to clang 16

```
/Users/runner/miniforge3/conda-bld/tiledb-vcf_1730387224701/work/libtiledbvcf/src/read/in_memory_exporter.cc:1019:17: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
 1019 |     int decoded[nelts];
      |                 ^~~~~
/Users/runner/miniforge3/conda-bld/tiledb-vcf_1730387224701/work/libtiledbvcf/src/read/in_memory_exporter.cc:1019:17: note: read of non-const variable 'nelts' is not allowed in a constant expression
/Users/runner/miniforge3/conda-bld/tiledb-vcf_1730387224701/work/libtiledbvcf/src/read/in_memory_exporter.cc:984:24: note: declared here
  984 |   uint64_t nbytes = 0, nelts = 0;
      |                        ^
1 error generated.
```

**Comment by dudoslav** [comment]
I think that we should pin to clang16 and perhaps fix it in the future.

**Comment by jdblischak** [comment]
@dudoslav pushed a commit to pin the osx builds to clang 16

**Review by jdblischak — APPROVED** [review]

**Pull request merged**
