### PR TITLE
Update TileDB-VCF to 0.37.0

### PR DESCRIPTION
**Pull request by gspowley**
Update TileDB-VCF to 0.37.0 and TileDB to 2.27.

### CODE REVIEW

**Review by jdblischak — APPROVED** [review]
Approved, but if you have time, I suggest rerendering the feedstock

**Comment by jdblischak** [comment]
Another note: In the last update PR https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/141, I pinned clang to 16 (https://github.com/TileDB-Inc/tiledb-vcf-feedstock/commit/bd18ae139f2e91d37117d10d150c722c85f32dc8). Now that upstream tiledb-feedstock was migrated from clang 16 to 18 (https://github.com/conda-forge/tiledb-feedstock/pull/367), and Dusan fixed the problem in TileDB-VCF (https://github.com/TileDB-Inc/tiledb-vcf-feedstock/issues/143#issuecomment-2460433864, https://github.com/TileDB-Inc/TileDB-VCF/pull/787), we should be able to migrate to clang 18. To do this, delete the 4 lines below and then rerender again:

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/d3eadffd41422a403427a48b392f2a3ab495874e/recipe/conda_build_config.yaml#L9-L12

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
Thinking ahead. If the recipe builds but the validation fails, you can fix this by disabling the conda-forge validation step (ie set to `false`)

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/d3eadffd41422a403427a48b392f2a3ab495874e/conda-forge.yml#L7

**Comment by jdblischak** [comment]
The error breaking the linux and osx-* builds is from the very beginning of the Python package build:

```python
TypeError: __init__() got an unexpected keyword argument 'version_file'
```

I assume that is coming from the setuptools-scm configuration in `pyproject.toml`:

https://github.com/TileDB-Inc/TileDB-VCF/blob/9ee592ddf81b9098d649f01dd5825763de68e7eb/apis/python/pyproject.toml#L69

But that code wasn't touched between 0.36 and 0.37, so I don't understand why it is surfacing now:

https://github.com/TileDB-Inc/TileDB-VCF/compare/0.36.0...0.37.0

**Comment by gspowley** [comment]
It looks like something in our dependencies changed today. 

An earlier Linux build [passed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41509&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=5310) all except the conda-forge validation. The latest Linux build [failed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41511&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=1599) to build with an error related to `setuptools_scm`.

**Comment by jdblischak** [comment]
Bizarre. The passing build installed setuptools-scm 7.1.0, and the failing one 8.1.0. But setuptools-scm was released way back in May! How is this changing between builds that ran a few hours apart?

https://github.com/pypa/setuptools-scm/releases/tag/v8.1.0
https://github.com/conda-forge/setuptools_scm-feedstock/pull/74

**Comment by gspowley** [comment]
> How is this changing between builds that ran a few hours apart?

Looking in to it now. Whatever changed causes the same build failure on my system.

**Comment by gspowley** [comment]
Very strange behavior. The build stopped failing on my system, so I reran and the CI jobs here and `linux` and `osx_arm64` passed, while `osx_64` failed (`win_64` fails for another reason, as expected).

**Comment by gspowley** [comment]
We do need setuptools_scm 8.1.0 to pick up https://github.com/pypa/setuptools-scm/pull/870 released in 8.0.0.

This may require a pin in the `pyproject.toml`.

**Pull request merged**
