### PR TITLE
Build bump to pick up htslib 1.20

### PR DESCRIPTION
**Pull request by ihnorton**
Build bump to pick up htslib 1.20 [sc-50311].

### CODE REVIEW

**Review by dudoslav — APPROVED** [review]
CICD Build log:

`    htslib:                   1.20-hc7ee5c1_2             tiledb     `

So LGTM

**Comment by ihnorton** [comment]
macOS osx_64 build hit:
```
2024-07-12T21:51:57.5050830Z + bash test-cli.sh
2024-07-12T21:52:05.8319530Z test-cli.sh: line 11: 17464 Illegal instruction: 4  tiledbvcf export --uri s3://tiledb-inc-demo-data/tiledbvcf-arrays/v4/vcf-samples-20 --regions chr1:1-100000 --sample-names v2-usVwJUmo,v2-WpXCYApL --output-format z --output-dir "$OUTDIR"
```
[rerun](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40295&view=results)

**Review by jdblischak — APPROVED** [review]

**Comment by jdblischak** [comment]
> macOS osx_64 build hit:

I am confused why we are getting this `Illegal instruction` error now. We successfully built this feedstock only last week (https://github.com/TileDB-Inc/tiledb-vcf-feedstock/commit/535c08910b810da9efdf43b6541c3306b74e8619), and the [osx-64 build passed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40261&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b). Given that this PR hasn't changed the TileDB-VCF source code, I don't see why we would need to suddenly change the `OSX_DEPLOYMENT_TARGET`.

**Comment by dudoslav** [comment]
@jdblischak We bumped up (released) `htslib` version to 1.20, and since the pin here is `>1.15` it got picked up and used here. So perhaps the illegal instruction comes from `htslib`

**Comment by jdblischak** [comment]
I ran the builds on my fork using the [latest commit](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=884&view=results) (which used htslib 1.20), and I also tried pinning [htslib to 1.19](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=885&view=results). Both failed with the `Illegal instruction` error.

This means that something has changed (either a conda dependency or something in the Azure image) since last Tuesday (July 9th) that is causing the error, and it isn't the update of htslib from 1.19 to 1.20.

**Comment by dudoslav** [comment]
I am not sure if this is correct but on azure pipelines I can see that the newest jobs run under MacOS 12.7.5 but the last pipeline that passed is also 12.7.5:

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40261&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=3001bc22-659c-4b49-91e9-8cb6ed43d4eb

**Comment by jdblischak** [comment]
> the newest jobs run under MacOS 12.7.5 but the last pipeline that passed is also 12.7.5

Agreed. The versions are the same, but the image has changed:

* [last passing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40261&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=3001bc22-659c-4b49-91e9-8cb6ed43d4eb): Current image version: '20240630.1'
* [currently failing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40307&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=08cdaf7d-c7d0-4a63-b14d-730227f9e637): Current image version: '20240707.1'

**Comment by ihnorton** [comment]
> Agreed. The versions are the same, but the image has changed:

This is a good clue. But toolchain versions seem the same, at least:

```
2024-07-09T13:21:12.4685960Z INFO: activate_clang_osx-64.sh made the following environmental changes:
2024-07-09T13:21:12.5271560Z +AR=x86_64-apple-darwin13.4.0-ar
2024-07-09T13:21:12.5331170Z +AS=x86_64-apple-darwin13.4.0-as
2024-07-09T13:21:12.5379450Z +CC=x86_64-apple-darwin13.4.0-clang
```
```
2024-07-13T07:40:56.3260770Z INFO: activate_clang_osx-64.sh made the following environmental changes:
2024-07-13T07:40:56.3790890Z +AR=x86_64-apple-darwin13.4.0-ar
2024-07-13T07:40:56.3791620Z +AS=x86_64-apple-darwin13.4.0-as
2024-07-13T07:40:56.3791960Z +CC=x86_64-apple-darwin13.4.0-clang
2024-07-13T07:40:56.3792440Z +CC_FOR_BUILD=/Users/runner/miniforge3/conda-bld/tiledb-vcf_1720856107208/_build_env/bin/x86_64-apple-darwin13.4.0-clang
```

> [last passing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40261&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=3001bc22-659c-4b49-91e9-8cb6ed43d4eb): Current image version: '20240630.1'

This one picked up htslib 1.20, so we know definitively that it was fine before even on 1.20.

**Comment by dudoslav** [comment]
VCF versions are the same between those two runs and also feedstocks diff is just build number.

**Comment by jdblischak** [comment]
The osx-64 build runs on "macOS-12"

https://github.com/TileDB-Inc/tiledb-vcf-feedstock/blob/535c08910b810da9efdf43b6541c3306b74e8619/.azure-pipelines/azure-pipelines-osx.yml#L8

Thus here is the PR that updated the image to version 20240707.1: https://github.com/actions/runner-images/pull/10196

Very few updates were made. Trying to think of potential problems for this error:

* CMake and vcpkg were updated
* AWS CLI and AWS Session Manager CLI were updated. I only mention these because the line that fails is accessing an array from S3

**Comment by jdblischak** [comment]
> Very few updates were made. Trying to think of potential problems for this error:

Ack. Reminding myself that this is a feedstock build. None of these updates should matter. All of the dependencies should be provided by conda.

**Comment by jdblischak** [comment]
I compared the conda packages installed in the test environment between the  [last passing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40261&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=3001bc22-659c-4b49-91e9-8cb6ed43d4eb) build and a [currently failing](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40307&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=08cdaf7d-c7d0-4a63-b14d-730227f9e637) build.

The conda packages that actually changed versions (as opposed to simply a new build) are: libcxx, c-ares, aws-crt-cpp, aws-c-io

Given that this appears to be a problem with the compilation, I investigated libcxx first. Turns out there was already an Issue open about this `Illegal instruction` error on osx-64 caused by libcxx 18 https://github.com/conda-forge/libcxx-feedstock/issues/162

Also potentially of interest is this PR that recently updated `MACOSX_DEPLOYMENT_TARGET` for libcxx https://github.com/conda-forge/libcxx-feedstock/pull/159

Full diff below:

```sh
$ grep htslib vcf-*
vcf-failing.txt:htslib:                   1.20-hcfc518d_2             tiledb
vcf-passing.txt:htslib:                   1.20-hcfc518d_2             tiledb

$ diff vcf-passing.txt vcf-failing.txt
1c1
< aws-c-auth:               0.7.22-he52cbe7_7           conda-forge
---
> aws-c-auth:               0.7.22-hdb02296_8           conda-forge
5,9c5,9
< aws-c-event-stream:       0.4.2-ha5205da_14           conda-forge
< aws-c-http:               0.8.2-hf609411_4            conda-forge
< aws-c-io:                 0.14.9-h9f49e27_5           conda-forge
< aws-c-mqtt:               0.10.4-hcc4e2a5_7           conda-forge
< aws-c-s3:                 0.6.0-h8fdb93b_0            conda-forge
---
> aws-c-event-stream:       0.4.2-h2713d70_15           conda-forge
> aws-c-http:               0.8.2-ha849b92_5            conda-forge
> aws-c-io:                 0.14.10-h9f49e27_0          conda-forge
> aws-c-mqtt:               0.10.4-hf6997d9_8           conda-forge
> aws-c-s3:                 0.6.0-hfc8374f_1            conda-forge
12,13c12,13
< aws-crt-cpp:              0.27.2-h7746516_0           conda-forge
< aws-sdk-cpp:              1.11.329-hce9e41e_8         conda-forge
---
> aws-crt-cpp:              0.27.3-hed18db7_1           conda-forge
> aws-sdk-cpp:              1.11.329-h554caeb_9         conda-forge
19c19
< c-ares:                   1.28.1-h10d778d_0           conda-forge
---
> c-ares:                   1.32.1-h51dda26_0           conda-forge
28c28
< libcxx:                   17.0.6-heb59cac_3           conda-forge
---
> libcxx:                   18.1.8-hef8daea_0           conda-forge
40c40
< libtiledbvcf:             0.33.2-hfffce77_0           local
---
> libtiledbvcf:             0.33.2-h4f7dbc7_1           local
42c42
< libxml2:                  2.12.7-h3e169fe_1           conda-forge
---
> libxml2:                  2.12.7-hc603aa4_3           conda-forge
49c49
< tiledb:                   2.24.2-h493d6f2_1           conda-forge
---
> tiledb:                   2.24.2-h86b3714_2           conda-forge
```

**Comment by dudoslav** [comment]
It seems that we only need to pin libcxx<18: https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/128

So I will add one last commit removing all other aws and similar pins

**Pull request merged**
